### ISSUE TITLE
Execution fails at creating symbolic link "/.m2" instead of "~/.m2"

### ISSUE THREAD

**Issue by bitgully** [paketo-buildpacks/maven#308]
I'm using [paketo-buildpacks/maven:6.15.11](https://github.com/paketo-buildpacks/maven/tree/v6.15.11) as part of the [paketobuildpacks/builder-jammy-tiny:0.0.211](https://github.com/paketo-buildpacks/builder-jammy-tiny/tree/v0.0.211) image in an unprivileged manner.
The execution fails because the buildpack tries to write to the root location but has no permission to do so.

Here is the log output: [log.txt](https://github.com/paketo-buildpacks/maven/files/13620241/log.txt)

## Expected Behavior
The paketo-buildpacks/maven should create it's symbolic link at "~/.m2" rather than under root.
The documentation also claims it would do so by the bullet point 
- Links the ~/.m2 to a layer for caching (see [here](https://github.com/paketo-buildpacks/maven/tree/v6.15.11)).

## Current Behavior
The buildpack tries to create the symbolic link "/.m2" and fails due to a lack of permission.

## Possible Solution
Always create symbolic links under the current user.
Allow defining alternative .m2 locations as mentioned in issue #58.

**Comment by dmikusa** [comment]
Off the top of my head, there's only two ways I could see this happening.

1. If you're running as root. Generally, that wouldn't happen. The `pack` cli isn't going to run the app as root. How are your running this app? With `pack`? If so, what is your `pack build` command. If not, how are you running the buildpacks?

2. If the library we use to fetch the user's home directory is not working correctly. We [fetch the user's home directory](https://github.com/paketo-buildpacks/maven/blob/main/maven/build.go#L104-L110) in Go, because `~/` is a shell thing, and the code in question isn't running in a shell so we can't rely on that. Calculating the home directory in a cross-platform way isn't as simple as it sounds, so it's possible that's not working right. Again, more details on how you're running the buildpacks would help us understand if/how thing might have happened.

Thanks

**Comment by bitgully** [comment]
Hi Daniel,

I'm not running as root but with the default UID 1000 and GID 1000.

The build is executed on Kubernetes as part of the "buildpacks" Tekton pipeline (https://hub.tekton.dev/tekton/task/buildpacks) version 0.6.
For demonstration purposes, I have attached an example of the Tekton "Task" and "TaskRun" resources.
The relevant part can be found in [buildpacks_tekton_task.txt](https://github.com/paketo-buildpacks/maven/files/13657933/buildpacks_tekton_task.txt) starting at line 138, where the "builder-jammy-tiny" container is executed.

Is it possible that the "runAs" user 1000 gets no home directory set and paketo-buildpacks/maven defaults to "/"?

Cheers

[buildpacks_tekton_taskrun.txt](https://github.com/paketo-buildpacks/maven/files/13657932/buildpacks_tekton_taskrun.txt)
[buildpacks_tekton_task.txt](https://github.com/paketo-buildpacks/maven/files/13657933/buildpacks_tekton_task.txt)
